# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('termo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('autor', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('conteudo_processado', models.TextField(blank=True, null=True)),
                ('editora', models.CharField(max_length=200)),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.Livro')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termo.Termo')),
            ],
        ),
        migrations.CreateModel(
            name='Similaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('livro_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_i', to='livro.Livro')),
                ('livro_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_j', to='livro.Livro')),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='similaridades',
            field=models.ManyToManyField(blank=True, through='livro.Similaridade', to='livro.Livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='termos',
            field=models.ManyToManyField(blank=True, related_name='termos', through='livro.Peso', to='termo.Termo'),
        ),
    ]
