# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaLivroSelecionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.Livro')),
            ],
        ),
        migrations.CreateModel(
            name='PesquisaRecomendacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BooleanField(default=True)),
                ('data', models.DateTimeField(auto_now=True)),
                ('recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.Livro', verbose_name='Livro recomendado')),
                ('selecionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.PesquisaLivroSelecionado')),
            ],
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pesquisa',
            name='livro',
        ),
        migrations.DeleteModel(
            name='Recomendacao',
        ),
        migrations.AddField(
            model_name='pesquisalivroselecionado',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Pesquisa'),
        ),
    ]
